DROP DATABASE IF EXISTS Camping;
CREATE DATABASE Camping;
DROP USER IF EXISTS camping;
CREATE USER IF NOT EXISTS camping
  IDENTIFIED BY 'camping';
USE Camping;

CREATE TABLE AUTHORIZATION (
  label VARCHAR(45) NOT NULL,
  PRIMARY KEY (label)
);

CREATE TABLE CLIENT (
  id        INTEGER     NOT NULL AUTO_INCREMENT,
  email     VARCHAR(45),
  firstname VARCHAR(45) NOT NULL,
  lastname  VARCHAR(45) NOT NULL,
  phone     VARCHAR(11),
  PRIMARY KEY (id)
);

CREATE TABLE CLIENT_PROBLEM (
  client_id  INTEGER NOT NULL,
  problem_id INTEGER NOT NULL,
  PRIMARY KEY (client_id, problem_id)
);

CREATE TABLE EMPLOYEE (
  id              INTEGER      NOT NULL AUTO_INCREMENT,
  completeAddress VARCHAR(255),
  email           VARCHAR(45),
  firstName       VARCHAR(255) NOT NULL,
  lastName        VARCHAR(255) NOT NULL,
  login           VARCHAR(20),
  password        VARCHAR(255),
  phone           VARCHAR(11),
  PRIMARY KEY (id)
);

CREATE TABLE EMPLOYEE_AUTHORIZATION (
  employee_id      INTEGER     NOT NULL,
  authorization_id VARCHAR(45) NOT NULL,
  PRIMARY KEY (employee_id, authorization_id)
);

CREATE TABLE EMPLOYEE_NOTIFICATION (
  employee_id     INTEGER NOT NULL,
  notification_id INTEGER NOT NULL,
  PRIMARY KEY (employee_id, notification_id)
);

CREATE TABLE LOCATION (
  id     INTEGER          NOT NULL AUTO_INCREMENT,
  name   VARCHAR(255),
  pointX DOUBLE PRECISION NOT NULL,
  pointY DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE LOCATION_PROBLEM (
  location_id INTEGER NOT NULL,
  problem_id  INTEGER NOT NULL,
  PRIMARY KEY (location_id, problem_id)
);

CREATE TABLE LOG (
  id          INTEGER      NOT NULL AUTO_INCREMENT,
  action      VARCHAR(255) NOT NULL,
  datetime    DATETIME     NOT NULL,
  employee_id INTEGER      NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE MAP (
  id    INTEGER  NOT NULL AUTO_INCREMENT,
  image LONGBLOB NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE NOTIFICATION (
  id      INTEGER      NOT NULL AUTO_INCREMENT,
  content VARCHAR(255) NOT NULL,
  title   VARCHAR(45)  NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE PROBLEM (
  id                 INTEGER      NOT NULL AUTO_INCREMENT,
  appearanceDatetime DATETIME     NOT NULL,
  description        VARCHAR(255) NOT NULL,
  solutionDatetime   DATETIME,
  PRIMARY KEY (id)
);

CREATE TABLE PRODUCT (
  id               INTEGER      NOT NULL AUTO_INCREMENT,
  criticalQuantity INTEGER      NOT NULL,
  name             VARCHAR(255) NOT NULL,
  sellPrice        FLOAT        NOT NULL,
  stock            INTEGER      NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE PURCHASE (
  id         INTEGER  NOT NULL AUTO_INCREMENT,
  datetime   DATETIME NOT NULL,
  quantity   INTEGER  NOT NULL,
  client_id  INTEGER  NOT NULL,
  product_id INTEGER  NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE RESERVATION (
  id              INTEGER  NOT NULL AUTO_INCREMENT,
  clientComment   VARCHAR(255),
  reduction       FLOAT    NOT NULL,
  endtime         DATETIME NOT NULL,
  personCount     INTEGER  NOT NULL,
  reservationDate DATETIME NOT NULL,
  starttime       DATETIME NOT NULL,
  client_id       INTEGER  NOT NULL,
  spot_id         INTEGER  NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE RESTOCKING (
  id          INTEGER  NOT NULL AUTO_INCREMENT,
  datetime    DATETIME NOT NULL,
  quantity    INTEGER  NOT NULL,
  product_id  INTEGER  NOT NULL,
  supplier_id INTEGER  NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE SPOT (
  capacity    INTEGER NOT NULL,
  electricity BIT     NOT NULL,
  pricePerDay FLOAT   NOT NULL,
  shadow      BIT     NOT NULL,
  water       BIT     NOT NULL,
  id          INTEGER NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE SUPPLIER (
  id      INTEGER      NOT NULL AUTO_INCREMENT,
  email   VARCHAR(255),
  name    VARCHAR(255) NOT NULL,
  phone   VARCHAR(255),
  website VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE SUPPLIER_PROPOSE_PRODUCT (
  id          INTEGER NOT NULL AUTO_INCREMENT,
  sellPrice   FLOAT   NOT NULL,
  product_id  INTEGER NOT NULL,
  supplier_id INTEGER NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE TASK (
  id          INTEGER      NOT NULL AUTO_INCREMENT,
  endtime     DATETIME     NOT NULL,
  label       VARCHAR(255) NOT NULL,
  starttime   DATETIME     NOT NULL,
  employee_id INTEGER      NOT NULL,
  location_id INTEGER,
  PRIMARY KEY (id)
);

ALTER TABLE EMPLOYEE
  ADD CONSTRAINT UK_7v1f89g44sb8vhqy4ok2bispy UNIQUE (login);

ALTER TABLE CLIENT_PROBLEM
  ADD CONSTRAINT FKaro9e5vltrvgj9fvdhcf0pr7e
FOREIGN KEY (problem_id)
REFERENCES PROBLEM (id);

ALTER TABLE CLIENT_PROBLEM
  ADD CONSTRAINT FKewlxful95rewo1oo2ank3wlhk
FOREIGN KEY (client_id)
REFERENCES CLIENT (id);

ALTER TABLE EMPLOYEE_AUTHORIZATION
  ADD CONSTRAINT FKev1uq9wohdkyukiywc9kbqe8a
FOREIGN KEY (authorization_id)
REFERENCES AUTHORIZATION (label);

ALTER TABLE EMPLOYEE_AUTHORIZATION
  ADD CONSTRAINT FKarrcc34wiu2p4gb2s2a0d4a3d
FOREIGN KEY (employee_id)
REFERENCES EMPLOYEE (id);

ALTER TABLE EMPLOYEE_NOTIFICATION
  ADD CONSTRAINT FKqengm5re9clbresmu9n44b54r
FOREIGN KEY (notification_id)
REFERENCES NOTIFICATION (id);

ALTER TABLE EMPLOYEE_NOTIFICATION
  ADD CONSTRAINT FKagpevu1qohk7ofiwo2mq37ocv
FOREIGN KEY (employee_id)
REFERENCES EMPLOYEE (id);

ALTER TABLE LOCATION_PROBLEM
  ADD CONSTRAINT FK79huk0l77wvmuuq8dyupf70jb
FOREIGN KEY (problem_id)
REFERENCES PROBLEM (id);

ALTER TABLE LOCATION_PROBLEM
  ADD CONSTRAINT FK36wlscpqnnu7hfj0v9h5vybjj
FOREIGN KEY (location_id)
REFERENCES LOCATION (id);

ALTER TABLE LOG
  ADD CONSTRAINT FKlraml1cyoakihshtt0d2fwyem
FOREIGN KEY (employee_id)
REFERENCES EMPLOYEE (id);

ALTER TABLE PURCHASE
  ADD CONSTRAINT FKqgsswa6fm68e01npu6x82i4ys
FOREIGN KEY (client_id)
REFERENCES CLIENT (id);

ALTER TABLE PURCHASE
  ADD CONSTRAINT FKequxp5ih1ypinp91jtaaqp0jp
FOREIGN KEY (product_id)
REFERENCES PRODUCT (id);

ALTER TABLE RESERVATION
  ADD CONSTRAINT FK9fe9ikuq3uj2ivu2kj46k0pia
FOREIGN KEY (client_id)
REFERENCES CLIENT (id);

ALTER TABLE RESERVATION
  ADD CONSTRAINT FK83mmgw4wy7137q65sf0tvged8
FOREIGN KEY (spot_id)
REFERENCES SPOT (id);

ALTER TABLE RESTOCKING
  ADD CONSTRAINT FKlamw26gpk37jo3y5sxqu6q8jv
FOREIGN KEY (product_id)
REFERENCES PRODUCT (id);

ALTER TABLE RESTOCKING
  ADD CONSTRAINT FK88d4f0eol61ikqrf8s56hh96e
FOREIGN KEY (supplier_id)
REFERENCES SUPPLIER (id);

ALTER TABLE SPOT
  ADD CONSTRAINT FKj92gxury8y6ro66t6310gxhyg
FOREIGN KEY (id)
REFERENCES LOCATION (id);

ALTER TABLE SUPPLIER_PROPOSE_PRODUCT
  ADD CONSTRAINT FKioers9ycmbonyn3ylj3u950sf
FOREIGN KEY (product_id)
REFERENCES PRODUCT (id);

ALTER TABLE SUPPLIER_PROPOSE_PRODUCT
  ADD CONSTRAINT FK6wr2xdori660ehg2hsxxmxopl
FOREIGN KEY (supplier_id)
REFERENCES SUPPLIER (id);

ALTER TABLE TASK
  ADD CONSTRAINT FKcjcuvxpetiu28vecbdpiriwd5
FOREIGN KEY (employee_id)
REFERENCES EMPLOYEE (id);

ALTER TABLE TASK
  ADD CONSTRAINT FK9y4w10ihe6vms9vgb9th4n7na
FOREIGN KEY (location_id)
REFERENCES LOCATION (id);

INSERT INTO AUTHORIZATION (label) VALUES
  ('CLIENT_READ'),
  ('CLIENT_UPDATE'),
  ('PROBLEM_READ'),
  ('PROBLEM_UPDATE'),
  ('EMPLOYEE_READ'),
  ('EMPLOYEE_UPDATE'),
  ('SUPPLIER_READ'),
  ('SUPPLIER_UPDATE'),
  ('PRODUCT_READ'),
  ('PRODUCT_UPDATE'),
  ('MAP_READ'),
  ('MAP_UPDATE'),
  ('RESERVATION_READ'),
  ('RESERVATION_UPDATE');
COMMIT;

REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'camping'@'%';
GRANT SELECT ON Camping.AUTHORIZATION TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.CLIENT TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.CLIENT_PROBLEM TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.EMPLOYEE TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.EMPLOYEE_AUTHORIZATION TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.EMPLOYEE_NOTIFICATION TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.EMPLOYEE_NOTIFICATION TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.LOCATION TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.LOCATION_PROBLEM TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.LOG TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.MAP TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.NOTIFICATION TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.PROBLEM TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.PRODUCT TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.PURCHASE TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.RESERVATION TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.RESTOCKING TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.SPOT TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.SUPPLIER TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.SUPPLIER_PROPOSE_PRODUCT TO 'camping'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON Camping.TASK TO 'camping'@'%';
  
